### ISSUE TITLE
file.001.xtm ... [FAILED]

### ISSUE THREAD

**Issue by Kcchouette** [hcartiaux/xtm#1]
```
$ xtm -i file.001.xtm -v
file.001.xtm ... [FAILED]
```

How can I investigate the error? cheers

**Comment by hcartiaux** [comment]
Hey, I would answer, with a debugger.

This was one of my first program in C that I wrote 18 years ago, I'm impressed someone actually tried to use it.

So, I will not debug it, sorry. From memory, xtrem-split was not a very professional tool, it was just an old windows freeware. I would not be surprised if the header structure had changed between versions.

You may have more chance with [TuXtremSplit](https://gitlab.com/zedtux/tuxtremsplit).

Good luck!
